services:
  - type: web
    name: teslamate
    runtime: docker
    repo: https://github.com/your-repo/teslamate.git
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENCRYPTION_KEY
        value: secretkey # replace with a secure key to encrypt your Tesla API tokens
      - key: DATABASE_USER
        value: teslamate
      - key: DATABASE_PASS
        value: password # insert your secure database password!
      - key: DATABASE_NAME
        value: teslamate
      - key: DATABASE_HOST
        value: database
      - key: MQTT_HOST
        value: mosquitto
    disk:
      name: teslamate-data
      mountPath: /opt/app/import
      sizeGB: 10

  - type: web
    name: database
    runtime: docker
    repo: https://github.com/your-repo/database.git
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: POSTGRES_USER
        value: teslamate
      - key: POSTGRES_PASSWORD
        value: password # insert your secure database password!
      - key: POSTGRES_DB
        value: teslamate
    disk:
      name: teslamate-db
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  - type: web
    name: grafana
    runtime: docker
    repo: https://github.com/your-repo/grafana.git
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_USER
        value: teslamate
      - key: DATABASE_PASS
        value: password # insert your secure database password!
      - key: DATABASE_NAME
        value: teslamate
      - key: DATABASE_HOST
        value: database
    disk:
      name: grafana-data
      mountPath: /var/lib/grafana
      sizeGB: 10

  - type: web
    name: mosquitto
    runtime: docker
    repo: https://github.com/your-repo/mosquitto.git
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: mosquitto -c /mosquitto-no-auth.conf
    disk:
      name: mosquitto-data
      mountPath: /mosquitto/data
      sizeGB: 10

databases:
  - name: teslamate-db
    databaseName: teslamate
    user: teslamate
    plan: starter
    region: oregon

envVarGroups:
  - name: teslamate-settings
    envVars:
      - key: ENCRYPTION_KEY
        value: secretkey # replace with a secure key to encrypt your Tesla API tokens
      - key: DATABASE_USER
        value: teslamate
      - key: DATABASE_PASS
        value: password # insert your secure database password!
      - key: DATABASE_NAME
        value: teslamate
      - key: DATABASE_HOST
        value: database
      - key: MQTT_HOST
        value: mosquitto
